### ISSUE TITLE
Implement four-arithmetic-operations

### ISSUE THREAD

**Issue by sungohki** [sungohki/four-arithmetic-operations#1]
### Description
Please describe about what you want to do

### Tasks
- [ ] Implement Add function
- [ ] Implement Subtract function
- [ ] Implement Divide function
- [ ] Implement Multiply function

### References
- [LinkTest] (Link Address)
