### ISSUE TITLE
implement: Subtract function

### ISSUE THREAD

**Issue by chamdduk** [sungohki/four-arithmetic-operations#2]
### Description
Implement Subtract function for arithmetic operations

### To-Do

- [ ] Input two argument from user
- [ ] Create new argument
- [ ] Subtract the second argument form the first argument from user and put the result into the new argument
